import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/view/header/page'
import Footer from '@/view/footer/page'
import Providers from '@/app/functionalComponents/Provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Vj Market',
  description: 'Generated by Kazim Hussain',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
      <Header />
      <main className='py-12'>
      {children}
      </main>
      <Footer />
      </Providers>
      </body>
    </html>
  )
}
